### ISSUE TITLE
[PE-D][Tester B] Missing Target user profile in DG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T18-2/tp#155]
Target user profile is not present in DG.
![Screenshot 2023-11-03 at 4.46.44 PM.jpg](https://raw.githubusercontent.com/DaDevChia/ped/main/files/4b56c84e-5e7e-48d5-bda4-01ad863ec054.jpg)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: DaDevChia/ped#1

**Comment by ryan1604** [comment]
Closed as completed in #197
