### ISSUE TITLE
[PE-D][Tester C] Error Message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T18-2/tp#170]
Not sure what this error message means. I think it could be printed more elegantly.

 
![Uploading Screenshot 2023-11-03 at 5.12.40 PM.png...Screenshot 2023-11-03 at 5.12.40 PM.png]

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: J0shuaLeong/ped#3

**Comment by ryan1604** [comment]
Can anyone see this

**Comment by wwweert123** [comment]
Cant

**Comment by ryan1604** [comment]
Closed
