### ISSUE TITLE
[PE-D][Tester F] Unclear error when `budget` is used with no arguments.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T18-2/tp#185]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
```
budget
Index 0 out of bounds for length 0
```

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: lctxct/ped#6

**Comment by ryan1604** [comment]
Closed as duplicate
