### ISSUE TITLE
[PE-D][Tester D] User Guide Empty Answer

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T18-2/tp#186]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![Screenshot 2023-11-03 at 18.06.17.png](https://raw.githubusercontent.com/Remy9926/ped/main/files/b84b9ce2-7e6d-4c73-9f93-37d1e828c7a3.png)

In the UG it does not explain how to transfer data to another computer

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Remy9926/ped#1

**Comment by ryan1604** [comment]
Closed as duplicate
