### ISSUE TITLE
[PE-D][Tester D] Make User Guide less cluttered

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T18-2/tp#187]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
As a suggestion, since there are many commands for the program as it is fairly large, for any commands that have similar prefixes, it would be neater and less cluttered to group them together as well as provide a list of suffixes that can follow the commands. This way, the user guide isn't so long and it takes a while to get through everything.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Remy9926/ped#2

**Comment by ryan1604** [comment]
Closed
